/* data.jsx — curated catalog + personal library seed (global: BX_DATA) */
(function () {
  const authors = {
    dawkins:  { id:"dawkins", name:"Richard Dawkins", born:1941, country:"United Kingdom",
      bio:"Evolutionary biologist and former Oxford professor for the Public Understanding of Science. His gene-centred view of evolution reframed how a generation of readers understands natural selection." },
    darwin:   { id:"darwin", name:"Charles Darwin", born:1809, country:"United Kingdom",
      bio:"English naturalist whose theory of evolution by natural selection became the unifying framework of the life sciences. His careful, patient prose still rewards close reading." },
    coyne:    { id:"coyne", name:"Jerry A. Coyne", born:1949, country:"United States",
      bio:"Evolutionary geneticist at the University of Chicago, known for clear, evidence-first writing aimed at the curious general reader." },
    weiner:   { id:"weiner", name:"Jonathan Weiner", born:1953, country:"United States",
      bio:"Pulitzer Prize–winning science writer who follows researchers into the field to tell evolution as a living, observable story." },
    shubin:   { id:"shubin", name:"Neil Shubin", born:1960, country:"United States",
      bio:"Paleontologist and anatomist who co-discovered Tiktaalik, the fish-with-limbs fossil that bridges water and land." },
    harari:   { id:"harari", name:"Yuval Noah Harari", born:1976, country:"Israel",
      bio:"Historian whose sweeping, big-history syntheses connect biology, culture, and economics across the human story." },
    diamond:  { id:"diamond", name:"Jared Diamond", born:1937, country:"United States",
      bio:"Geographer and physiologist who argues that environment, more than innate difference, shaped the fates of human societies." },
    hawking:  { id:"hawking", name:"Stephen Hawking", born:1942, country:"United Kingdom",
      bio:"Theoretical physicist who brought black holes and the origins of the cosmos to millions of lay readers." },
    rovelli:  { id:"rovelli", name:"Carlo Rovelli", born:1956, country:"Italy",
      bio:"Theoretical physicist and a founder of loop quantum gravity, celebrated for spare, poetic science writing." },
    hofstadter:{ id:"hofstadter", name:"Douglas Hofstadter", born:1945, country:"United States",
      bio:"Cognitive scientist whose playful, recursive masterwork links logic, art, and the nature of mind." },
    sagan:    { id:"sagan", name:"Carl Sagan", born:1934, country:"United States",
      bio:"Astronomer and the great popularizer of science, whose sense of cosmic wonder reached a global audience." },
    aurelius: { id:"aurelius", name:"Marcus Aurelius", born:121, country:"Roman Empire",
      bio:"Roman emperor and Stoic philosopher whose private notebook became one of the most enduring guides to a steady life." },
    nietzsche:{ id:"nietzsche", name:"Friedrich Nietzsche", born:1844, country:"Germany",
      bio:"Philosopher and philologist whose aphoristic, incendiary work questioned morality, truth, and meaning." },
    marquez:  { id:"marquez", name:"Gabriel García Márquez", born:1927, country:"Colombia",
      bio:"Nobel laureate and central figure of magical realism, whose novels fold the marvelous into everyday life." },
    dostoevsky:{ id:"dostoevsky", name:"Fyodor Dostoevsky", born:1821, country:"Russia",
      bio:"Russian novelist who plumbed guilt, faith, and freedom with unmatched psychological intensity." },
    morrison: { id:"morrison", name:"Toni Morrison", born:1931, country:"United States",
      bio:"Nobel laureate whose lyrical, unflinching novels center Black American life and memory." },
    mccarthy: { id:"mccarthy", name:"Cormac McCarthy", born:1933, country:"United States",
      bio:"American novelist of stark, biblical prose and a bleak moral vision of the American landscape." },
    eliot:    { id:"eliot", name:"George Eliot", born:1819, country:"United Kingdom",
      bio:"Pen name of Mary Ann Evans, whose realist novels render provincial life with deep moral seriousness." },
    woolf:    { id:"woolf", name:"Virginia Woolf", born:1882, country:"United Kingdom",
      bio:"Modernist pioneer of stream-of-consciousness, mapping the inner weather of ordinary days." },
    calvino:  { id:"calvino", name:"Italo Calvino", born:1923, country:"Italy",
      bio:"Italian fabulist whose inventive, structurally daring fictions read like philosophical games." },
    tuchman:  { id:"tuchman", name:"Barbara W. Tuchman", born:1912, country:"United States",
      bio:"Two-time Pulitzer historian who wrote narrative history with the pace and texture of a novel." },
    beard:    { id:"beard", name:"Mary Beard", born:1955, country:"United Kingdom",
      bio:"Cambridge classicist who makes the ancient world vivid, argued-over, and surprisingly modern." },
    judt:     { id:"judt", name:"Tony Judt", born:1948, country:"United Kingdom",
      bio:"Historian of modern Europe whose magisterial postwar account combined scholarship with moral clarity." },
    kahneman: { id:"kahneman", name:"Daniel Kahneman", born:1934, country:"Israel",
      bio:"Psychologist and Nobel economics laureate who mapped the two systems behind human judgment." },
    gleick:   { id:"gleick", name:"James Gleick", born:1954, country:"United States",
      bio:"Science writer who traces big ideas — chaos, information, time — through the people who chased them." },
  };

  // s = subjects, m = moods. hue = cover background.
  const B = (o) => o;
  const books = [
    B({ id:"selfish-gene", title:"The Selfish Gene", authorId:"dawkins", year:1976, publisher:"Oxford University Press",
      s:["Evolution","Biology","Science"], m:["Mind-expanding","Rigorous","Accessible"], pages:360, rating:4.2, hue:"#6f7a55",
      blurb:"The argument that the gene, not the organism, is the fundamental unit on which selection acts." }),
    B({ id:"origin-species", title:"On the Origin of Species", authorId:"darwin", year:1859, publisher:"John Murray",
      s:["Evolution","Biology","Science"], m:["Challenging","Rigorous"], pages:502, rating:4.0, hue:"#5c6b72",
      blurb:"The founding work of evolutionary biology, laying out descent with modification by natural selection." }),
    B({ id:"why-evolution-true", title:"Why Evolution Is True", authorId:"coyne", year:2009, publisher:"Viking",
      s:["Evolution","Biology","Science"], m:["Accessible","Rigorous"], pages:282, rating:4.1, hue:"#7e6b3a",
      blurb:"A working geneticist's tour of the evidence — fossils, genes, biogeography — that makes evolution a fact." }),
    B({ id:"beak-finch", title:"The Beak of the Finch", authorId:"weiner", year:1994, publisher:"Alfred A. Knopf",
      s:["Evolution","Biology","Science"], m:["Lyrical","Accessible"], pages:332, rating:4.1, hue:"#8a6d3b",
      blurb:"Evolution caught in the act on the Galápagos, following decades of finch fieldwork in real time." }),
    B({ id:"your-inner-fish", title:"Your Inner Fish", authorId:"shubin", year:2008, publisher:"Pantheon",
      s:["Evolution","Anatomy","Science"], m:["Playful","Accessible","Mind-expanding"], pages:240, rating:4.1, hue:"#5f7468",
      blurb:"How the human body still carries the engineering of fish, worms, and microbes in its bones and genes." }),
    B({ id:"sapiens", title:"Sapiens", authorId:"harari", year:2011, publisher:"Harvill Secker",
      s:["Anthropology","History","Science"], m:["Mind-expanding","Accessible","Epic"], pages:443, rating:4.4, hue:"#9c5b34",
      blurb:"A brisk big-history of how an unremarkable ape came to dominate the planet through shared fictions." }),
    B({ id:"guns-germs-steel", title:"Guns, Germs, and Steel", authorId:"diamond", year:1997, publisher:"W. W. Norton",
      s:["Anthropology","History","Science"], m:["Mind-expanding","Rigorous"], pages:480, rating:4.0, hue:"#7a5230",
      blurb:"Why some societies conquered others, argued from geography, crops, and disease rather than innate difference." }),
    B({ id:"brief-history-time", title:"A Brief History of Time", authorId:"hawking", year:1988, publisher:"Bantam Books",
      s:["Physics","Cosmology","Science"], m:["Mind-expanding","Challenging"], pages:212, rating:4.2, hue:"#2f3a4a",
      blurb:"From the Big Bang to black holes, the deep questions of modern cosmology for the general reader." }),
    B({ id:"order-of-time", title:"The Order of Time", authorId:"rovelli", year:2017, publisher:"Adelphi / Riverhead",
      s:["Physics","Philosophy","Science"], m:["Lyrical","Meditative","Mind-expanding"], pages:240, rating:4.1, hue:"#4a5560",
      blurb:"A physicist dismantles our intuition of time, and rebuilds it as something stranger and more beautiful." }),
    B({ id:"geb", title:"Gödel, Escher, Bach", authorId:"hofstadter", year:1979, publisher:"Basic Books",
      s:["Mathematics","Philosophy","Science"], m:["Playful","Challenging","Mind-expanding"], pages:777, rating:4.3, hue:"#815065",
      blurb:"A sprawling meditation on how meaning and mind emerge from formal systems, told through logic, art, and music." }),
    B({ id:"cosmos", title:"Cosmos", authorId:"sagan", year:1980, publisher:"Random House",
      s:["Cosmology","Physics","Science"], m:["Lyrical","Accessible","Mind-expanding"], pages:365, rating:4.4, hue:"#3c4a63",
      blurb:"A luminous tour of the universe and our small, precious place within it." }),
    B({ id:"meditations", title:"Meditations", authorId:"aurelius", year:180, publisher:"Modern Library (trans.)",
      s:["Philosophy","Stoicism"], m:["Meditative","Comforting","Challenging"], pages:256, rating:4.4, hue:"#6b5638",
      blurb:"A Roman emperor's private notes to himself on duty, mortality, and keeping a steady mind." }),
    B({ id:"zarathustra", title:"Thus Spoke Zarathustra", authorId:"nietzsche", year:1883, publisher:"Ernst Schmeitzner",
      s:["Philosophy"], m:["Challenging","Lyrical"], pages:352, rating:3.9, hue:"#4a4a4a",
      blurb:"A prophet descends from the mountains to proclaim the overman, eternal recurrence, and a revaluation of values." }),
    B({ id:"hundred-years", title:"One Hundred Years of Solitude", authorId:"marquez", year:1967, publisher:"Editorial Sudamericana",
      s:["Literary Fiction"], m:["Lyrical","Epic","Mind-expanding"], pages:417, rating:4.3, hue:"#a06a2c",
      blurb:"Seven generations of the Buendía family rise and fall in the mythical town of Macondo." }),
    B({ id:"crime-punishment", title:"Crime and Punishment", authorId:"dostoevsky", year:1866, publisher:"The Russian Messenger",
      s:["Literary Fiction","Russian Literature"], m:["Bleak","Challenging","Mind-expanding"], pages:671, rating:4.3, hue:"#6e2f2f",
      blurb:"A destitute student murders a pawnbroker and then must live inside his own conscience." }),
    B({ id:"karamazov", title:"The Brothers Karamazov", authorId:"dostoevsky", year:1880, publisher:"The Russian Messenger",
      s:["Literary Fiction","Russian Literature","Philosophy"], m:["Challenging","Epic","Mind-expanding"], pages:824, rating:4.4, hue:"#5a2a2a",
      blurb:"Faith, doubt, and patricide collide among three brothers in Dostoevsky's final, largest novel." }),
    B({ id:"beloved", title:"Beloved", authorId:"morrison", year:1987, publisher:"Alfred A. Knopf",
      s:["Literary Fiction"], m:["Bleak","Lyrical","Challenging"], pages:324, rating:4.0, hue:"#7a3b48",
      blurb:"A formerly enslaved woman is haunted — literally — by the daughter she could not let live in bondage." }),
    B({ id:"blood-meridian", title:"Blood Meridian", authorId:"mccarthy", year:1985, publisher:"Random House",
      s:["Literary Fiction"], m:["Bleak","Lyrical","Challenging"], pages:351, rating:4.2, hue:"#6b4a2f",
      blurb:"A nameless boy rides with a scalp-hunting gang across a hallucinatory, blood-soaked borderland." }),
    B({ id:"the-road", title:"The Road", authorId:"mccarthy", year:2006, publisher:"Alfred A. Knopf",
      s:["Literary Fiction"], m:["Bleak","Lyrical","Comforting"], pages:287, rating:4.2, hue:"#54585a",
      blurb:"A father and son walk a dead, ashen continent, carrying the fire of their love for each other." }),
    B({ id:"middlemarch", title:"Middlemarch", authorId:"eliot", year:1872, publisher:"William Blackwood and Sons",
      s:["Literary Fiction"], m:["Challenging","Meditative"], pages:904, rating:4.2, hue:"#5c6b4f",
      blurb:"The intertwined lives of a provincial English town, and the gap between great hopes and ordinary fates." }),
    B({ id:"mrs-dalloway", title:"Mrs Dalloway", authorId:"woolf", year:1925, publisher:"Hogarth Press",
      s:["Literary Fiction"], m:["Lyrical","Meditative"], pages:194, rating:3.9, hue:"#5a6675",
      blurb:"A single June day in London, told from inside the minds of a hostess and a shell-shocked veteran." }),
    B({ id:"to-the-lighthouse", title:"To the Lighthouse", authorId:"woolf", year:1927, publisher:"Hogarth Press",
      s:["Literary Fiction"], m:["Lyrical","Meditative","Challenging"], pages:209, rating:4.0, hue:"#496170",
      blurb:"Time, memory, and a family's summers by the sea, rendered in luminous stream of consciousness." }),
    B({ id:"invisible-cities", title:"Invisible Cities", authorId:"calvino", year:1972, publisher:"Einaudi",
      s:["Literary Fiction","Philosophy"], m:["Lyrical","Playful","Meditative"], pages:165, rating:4.2, hue:"#3f6f73",
      blurb:"Marco Polo describes impossible cities to Kublai Khan — each a meditation on memory, desire, and signs." }),
    B({ id:"guns-of-august", title:"The Guns of August", authorId:"tuchman", year:1962, publisher:"Macmillan",
      s:["History"], m:["Epic","Rigorous","Accessible"], pages:511, rating:4.2, hue:"#7c5a32",
      blurb:"The first month of World War I, narrated with the suspense of a thriller and the rigor of a historian." }),
    B({ id:"spqr", title:"SPQR: A History of Ancient Rome", authorId:"beard", year:2015, publisher:"Profile Books",
      s:["History"], m:["Accessible","Rigorous"], pages:606, rating:4.0, hue:"#8a3f33",
      blurb:"A thousand years of Rome, told with skepticism toward the myths Rome told about itself." }),
    B({ id:"postwar", title:"Postwar", authorId:"judt", year:2005, publisher:"The Penguin Press",
      s:["History"], m:["Epic","Rigorous","Challenging"], pages:933, rating:4.4, hue:"#4f5a4a",
      blurb:"Europe from 1945 to the present — politics, culture, and memory — in one commanding narrative." }),
    B({ id:"thinking-fast-slow", title:"Thinking, Fast and Slow", authorId:"kahneman", year:2011, publisher:"Farrar, Straus and Giroux",
      s:["Psychology","Economics","Science"], m:["Mind-expanding","Rigorous","Accessible"], pages:499, rating:4.1, hue:"#3f4a55",
      blurb:"The two systems of the mind — fast intuition and slow reason — and the biases that come with them." }),
    B({ id:"the-information", title:"The Information", authorId:"gleick", year:2011, publisher:"Pantheon",
      s:["Science","History","Mathematics"], m:["Mind-expanding","Challenging"], pages:526, rating:4.0, hue:"#46566b",
      blurb:"From drums to bits, a history of how humanity learned to encode, store, and transmit information." }),
  ];

  // hand-curated related links (by id) — falls back to subject overlap when absent
  const related = {
    "selfish-gene":["why-evolution-true","origin-species","your-inner-fish","geb"],
    "origin-species":["selfish-gene","why-evolution-true","beak-finch"],
    "why-evolution-true":["selfish-gene","beak-finch","your-inner-fish"],
    "beak-finch":["why-evolution-true","origin-species","your-inner-fish"],
    "your-inner-fish":["selfish-gene","why-evolution-true","beak-finch"],
    "sapiens":["guns-germs-steel","selfish-gene","thinking-fast-slow"],
    "guns-germs-steel":["sapiens","spqr","the-information"],
    "brief-history-time":["cosmos","order-of-time","geb"],
    "order-of-time":["brief-history-time","cosmos","invisible-cities"],
    "geb":["the-information","brief-history-time","thinking-fast-slow"],
    "cosmos":["brief-history-time","order-of-time","sapiens"],
    "meditations":["zarathustra","order-of-time"],
    "zarathustra":["meditations","karamazov"],
    "hundred-years":["invisible-cities","beloved","middlemarch"],
    "crime-punishment":["karamazov","beloved","blood-meridian"],
    "karamazov":["crime-punishment","middlemarch","zarathustra"],
    "beloved":["the-road","crime-punishment","hundred-years"],
    "blood-meridian":["the-road","crime-punishment"],
    "the-road":["blood-meridian","beloved","crime-punishment"],
    "middlemarch":["mrs-dalloway","karamazov","to-the-lighthouse"],
    "mrs-dalloway":["to-the-lighthouse","middlemarch","invisible-cities"],
    "to-the-lighthouse":["mrs-dalloway","middlemarch","invisible-cities"],
    "invisible-cities":["order-of-time","mrs-dalloway","hundred-years"],
    "guns-of-august":["spqr","postwar","sapiens"],
    "spqr":["guns-of-august","postwar","sapiens"],
    "postwar":["guns-of-august","spqr","the-information"],
    "thinking-fast-slow":["geb","sapiens","the-information"],
    "the-information":["geb","thinking-fast-slow","postwar"],
  };

  // personal library seed: status = queued | reading | finished | abandoned ; plus notes / userRating / userRelated
  const library = {
    "selfish-gene":   { status:"finished", userRating:5, dateAdded:"2024-11-02", notes:"The 'replicator vs. vehicle' chapter reframed everything for me. Reread the endnotes.", userRelated:["cosmos"] },
    "sapiens":        { status:"finished", userRating:4, dateAdded:"2024-09-18", notes:"Great first two-thirds; the futurism at the end is shakier.", userRelated:["postwar"] },
    "meditations":    { status:"finished", userRating:5, dateAdded:"2023-12-30", notes:"Book II and Book V are the ones I return to." },
    "cosmos":         { status:"finished", userRating:5, dateAdded:"2024-01-22", notes:"" },
    "crime-punishment":{ status:"finished", userRating:4, dateAdded:"2023-06-11", notes:"Raskolnikov's fever scenes are unforgettable." },
    "your-inner-fish":{ status:"finished", userRating:4, dateAdded:"2025-02-14", notes:"" },
    "guns-of-august": { status:"finished", userRating:4, dateAdded:"2024-07-04", notes:"" },
    "order-of-time":  { status:"reading", userRating:0, dateAdded:"2025-04-01", notes:"On chapter 4. Slow, in a good way." },
    "karamazov":      { status:"reading", userRating:0, dateAdded:"2025-03-12", notes:"The Grand Inquisitor — stop and reread." },
    "why-evolution-true":{ status:"queued", userRating:0, dateAdded:"2025-05-02", notes:"" },
    "thinking-fast-slow":{ status:"queued", userRating:0, dateAdded:"2025-05-10", notes:"" },
    "beloved":        { status:"queued", userRating:0, dateAdded:"2025-04-20", notes:"" },
    "postwar":        { status:"queued", userRating:0, dateAdded:"2025-05-21", notes:"Hardcover if I can find it." },
    "blood-meridian": { status:"queued", userRating:0, dateAdded:"2025-05-22", notes:"" },
    "zarathustra":    { status:"abandoned", userRating:2, dateAdded:"2024-03-15", notes:"Put it down in the second part. The aphorisms dazzle; the whole exhausts. Maybe another year." },
    "middlemarch":    { status:"abandoned", userRating:0, dateAdded:"2024-10-08", notes:"Stalled around the Casaubon honeymoon. Everyone tells me to push through." },
  };

  // ---- enriched edition metadata + AI-style category seeds ----
  // AI categories: evocative micro-genres distinct from the broad subject tags.
  const genres = {
    "selfish-gene":["Popular Science","Evolutionary Theory","Paradigm-Shifter"],
    "origin-species":["Foundational Science","Victorian Naturalism","Scientific Classic"],
    "why-evolution-true":["Popular Science","Evidence & Argument","Science Explainer"],
    "beak-finch":["Narrative Science","Field Biology","Evolution in Real Time"],
    "your-inner-fish":["Popular Science","Anatomy & Origins","Playful Nonfiction"],
    "sapiens":["Big History","Speculative Nonfiction","Grand Narrative"],
    "guns-germs-steel":["Big History","Geographic Determinism","Civilizational Sweep"],
    "brief-history-time":["Popular Cosmology","Mind-Bending Physics","Science Classic"],
    "order-of-time":["Poetic Physics","Philosophy of Time","Lyrical Science"],
    "geb":["Cognitive Science","Recursive Puzzle-Book","Intellectual Maze"],
    "cosmos":["Popular Astronomy","Cosmic Wonder","Science Humanism"],
    "meditations":["Stoic Philosophy","Personal Aphorisms","Ancient Wisdom"],
    "zarathustra":["Philosophical Prose-Poem","Existential Provocation","Prophetic Fiction"],
    "hundred-years":["Magical Realism","Multigenerational Saga","Latin American Boom"],
    "crime-punishment":["Psychological Drama","Crime & Conscience","Russian Realism"],
    "karamazov":["Philosophical Novel","Family Saga","Faith & Doubt"],
    "beloved":["Historical Fiction","Ghost Story","Trauma Narrative"],
    "blood-meridian":["Anti-Western","Literary Violence","Frontier Epic"],
    "the-road":["Post-Apocalyptic","Father & Son","Literary Survival"],
    "middlemarch":["Victorian Realism","Provincial Panorama","Moral Drama"],
    "mrs-dalloway":["Modernist Fiction","Stream of Consciousness","A Single Day"],
    "to-the-lighthouse":["Modernist Fiction","Memory & Time","Family Portrait"],
    "invisible-cities":["Fabulist Fiction","Prose Poetry","Philosophical Game"],
    "guns-of-august":["Narrative History","The Great War","History as Thriller"],
    "spqr":["Narrative History","Ancient Rome","Myth-Busting Scholarship"],
    "postwar":["Narrative History","Modern Europe","Magisterial Survey"],
    "thinking-fast-slow":["Behavioral Science","Decision-Making","Cognitive Bias"],
    "the-information":["History of Ideas","Information Theory","Big Concept"],
  };
  const themes = {
    "selfish-gene":["altruism & selfishness","units of selection","cooperation","determinism"],
    "origin-species":["common descent","adaptation","struggle for existence","deep time"],
    "why-evolution-true":["evidence & proof","common ancestry","vestigial traits","science vs. belief"],
    "beak-finch":["selection in action","adaptation","scientific patience","island ecology"],
    "your-inner-fish":["shared ancestry","the body as history","deep time","anatomy of change"],
    "sapiens":["shared fictions","cooperation at scale","power & progress","the pursuit of happiness"],
    "guns-germs-steel":["geography as destiny","inequality of nations","disease & conquest","domestication"],
    "brief-history-time":["origin of the universe","the nature of time","black holes","a theory of everything"],
    "order-of-time":["the illusion of time","memory & identity","entropy","perception of reality"],
    "geb":["self-reference","consciousness","formal systems","meaning & symbols"],
    "cosmos":["the cosmic perspective","our place in the universe","wonder & curiosity","science & reason"],
    "meditations":["mortality","self-discipline","duty","acceptance"],
    "zarathustra":["the will to power","eternal recurrence","self-overcoming","meaning after god"],
    "hundred-years":["solitude","cyclical time","memory & forgetting","fate & family"],
    "crime-punishment":["guilt & redemption","crime & conscience","poverty","free will"],
    "karamazov":["faith & doubt","free will","the suffering of innocents","patricide & guilt"],
    "beloved":["memory & trauma","motherhood","the legacy of slavery","haunting of the past"],
    "blood-meridian":["violence & fate","war as eternal","the moral void","the sublime & terrible"],
    "the-road":["love & survival","hope amid ruin","fatherhood","carrying the fire"],
    "middlemarch":["thwarted ambition","marriage","provincial society","idealism vs. reality"],
    "mrs-dalloway":["time & memory","the inner life","mortality","social surfaces"],
    "to-the-lighthouse":["memory & loss","the passage of time","art & permanence","family"],
    "invisible-cities":["memory & desire","cities as signs","imagination","impermanence"],
    "guns-of-august":["miscalculation","the inevitability of war","leadership","the momentum of events"],
    "spqr":["power & citizenship","empire","myth vs. history","the idea of rome"],
    "postwar":["memory & reckoning","reconstruction","division & unity","modern identity"],
    "thinking-fast-slow":["intuition vs. reason","cognitive bias","judgment under uncertainty","the illusion of understanding"],
    "the-information":["encoding meaning","from data to knowledge","communication","the information age"],
  };
  const langs = {
    "meditations":"English · trans. Greek",
    "zarathustra":"English · trans. German",
    "hundred-years":"English · trans. Spanish",
    "crime-punishment":"English · trans. Russian",
    "karamazov":"English · trans. Russian",
    "invisible-cities":"English · trans. Italian",
    "order-of-time":"English · trans. Italian",
  };
  function isbn13(id) {
    let h = 2166136261;
    for (let i = 0; i < id.length; i++) { h ^= id.charCodeAt(i); h = Math.imul(h, 16777619) >>> 0; }
    let body = ("978" + String(h).padStart(9, "0")).slice(0, 12);
    body = (body + "000000000000").slice(0, 12);
    let sum = 0;
    for (let i = 0; i < 12; i++) sum += (+body[i]) * (i % 2 ? 3 : 1);
    const d = body + ((10 - (sum % 10)) % 10);
    return `${d.slice(0,3)}-${d.slice(3,4)}-${d.slice(4,8)}-${d.slice(8,12)}-${d.slice(12)}`;
  }
  books.forEach(b => {
    b.lang = langs[b.id] || "English";
    b.isbn = isbn13(b.id);
    b.genres = genres[b.id] || b.s.slice(0, 3);
    b.themes = themes[b.id] || [];
    b.gbooks = "https://www.google.com/search?tbm=bks&q=" + encodeURIComponent(`${b.title} ${authors[b.authorId].name}`);
  });

  window.BX_DATA = { authors, books, related, library };
})();
